package com.example.springsecuritymaster12102022.security;

public interface SecurityRole {
    String ROLE_PREFIX = "ROLE_";
    String SUPER_ADMIN = "SUPER_ADMIN";
    String CUSTOMERS_ADMIN = "CUSTOMERS_ADMIN";
    String CUSTOMERS_READ = "CUSTOMERS_READ";
    String CUSTOMERS_CREATE = "CUSTOMERS_CREATE";
    String CUSTOMERS_DELETE = "CUSTOMERS_DELETE";
    String CUSTOMERS_PAGE_VIEW = "CUSTOMERS_PAGE_VIEW";

    String DEPARTMENT_ADMIN = "DEPARTMENT_ADMIN";
    String DEPARTMENT_READ = "DEPARTMENT_READ";
    String DEPARTMENT_CREATE = "DEPARTMENT_CREATE";
    String DEPARTMENT_DELETE = "DEPARTMENT_DELETE";
    String DEPARTMENT_PAGE_VIEW = "DEPARTMENT_PAGE_VIEW";

    String EMPLOYEES_ADMIN = "EMPLOYEES_ADMIN";
    String EMPLOYEES_READ = "EMPLOYEES_READ";
    String EMPLOYEES_CREATE = "EMPLOYEES_CREATE";
    String EMPLOYEES_DELETE = "EMPLOYEES_DELETE";
    String EMPLOYEES_PAGE_VIEW = "EMPLOYEES_PAGE_VIEW";
}
